version: '3.5'

services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    ports:
      - '1883:1883'
    networks:
      - default
    restart: unless-stopped

networks:
  default:
